export enum ACTIVE_TYPE {
    ADD_USERS = 'ADD-USERS',
}
export enum PROFILE_TYPE {
    SET_PROFILE = 'SET-PROFILE',
    CLEAN_PROFILE = 'CLEAN-PROFILE',
    GET_PROFILE = 'GET-PROFILE',
    ADD_POST = 'ADD-POST',
    DELETE_POST = 'DELETE-POST',
    LIKE_POST = 'LIKE-POST',
    FOLLOW = 'FOLLOW',
}

export enum AUTH_TYPES {
    LOGIN = 'LOGIN',
    SIGN_UP = 'SIGN-UP',
    LOGOUT = 'LOGOUT',
    CHECK_AUTH = 'CHECK-AUTH',
    NEED_AUTH = 'NEED_AUTH',
    SET_USER = 'SET-USER',
    CLEAN_USER = 'CLEAN_USER',
}

export enum ERROR_TYPES {
    SET_ERROR = 'SET-ERROR',
    GET_ERROR = 'GET-ERROR',
    REMOVE_ERROR = 'REMOVE-ERROR',
}
export enum CHAT_TYPES {
    SET_CHAT_LIST = 'SET_CHAT_LIST',
    GET_CHAT_LIST = 'GET_CHAT_LIST',
    CREATE_CHAT_LIST = 'CREATE_CHAT_LIST',
    GET_CHAT = 'GET_CHAT',
    SET_CHAT = 'SET_CHAT',
    SEND_MESSAGE = 'SEND_MESSAGE',
    SET_MESSAGE = 'SET_MESSAGE',
}
