export enum ACTIVE_TYPE {
    ADD_USERS = 'ADD-USERS',
}
export enum PROFILE_TYPE {
    SET_PROFILE = 'SET-PROFILE',
    CLEAN_PROFILE = 'CLEAN-PROFILE',
    GET_PROFILE = 'GET-PROFILE',
    ADD_POST = 'ADD-POST',
    SET_POST = 'SET-POST',
    DELETE_POST = 'DELETE-POST',
}

export enum AUTH_TYPES {
    LOGIN = 'LOGIN',
    SIGN_UP = 'SIGN-UP',
    LOGOUT = 'LOGOUT',
    CHECK_AUTH = 'CHECK-AUTH',
    NEED_AUTH = 'NEED_AUTH',
    SET_USER = 'SET-USER',
    CLEAN_USER = 'CLEAN_USER',
}
