export const SOCKET_URL = 'http://localhost:5000/';

export enum SOCKET_CONSTANTS {
    JOIN_PROFILE = 'JOIN-PROFILE',
    UPDATE_PROFILE = 'UPDATE-PROFILE',
    CHANGE_POST = 'CHANGE-POST',
    CHANGE_PROFILE = 'CHANGE_PROFILE',
    CHANGE_POST_TEXT = 'CHANGE-POST-TEXT',
    UPDATE_POST_TEXT = 'UPDATE-POST-TEXT',
    JOIN_CHAT = 'JOIN-CHAT',
    UPDATE_CHAT = 'UPDATE-CHAT',
    ADD_MESSAGE = 'ADD-MESSAGE',
    PRINTING_MESSAGE = 'PRINTING-MESSAGE',
    UPDATE_MESSAGE = 'UPDATE-MESSAGE',
}
